GestorAduana-v1/Controllers/BackOfficeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestorAduana_v1.Context;

namespace GestorAduana_v1.Controllers
{
    [Authorize(Roles = "Administrador,Gestor,BackOffice")]
    public class BackOfficeController : Controller
    {
        private GestorAduanasContext db = new GestorAduanasContext();

        // GET: BackOffice
        public ActionResult Index()
        {
            var backOffices = db.BackOffices.Include(b => b.Empresa);
            return View(backOffices.ToList());
        }

        // GET: BackOffice/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BackOffice backOffice = db.BackOffices.Find(id);
            if (backOffice == null)
            {
                return HttpNotFound();
            }
            return View(backOffice);
        }

        // GET: BackOffice/Create
        public ActionResult Create()
        {
            ViewBag.EmpresaId = new SelectList(db.Empresas, "EmpresaId", "Nombre");
            return View();
        }

        // POST: BackOffice/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdBackOffice,NombreBo,ApellidoBo,EmpresaId,Recorrido")] BackOffice backOffice)
        {
            if (ModelState.IsValid)
            {
                db.BackOffices.Add(backOffice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpresaId = new SelectList(db.Empresas, "EmpresaId", "Nombre", backOffice.EmpresaId);
            return View(backOffice);
        }

        // GET: BackOffice/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BackOffice backOffice = db.BackOffices.Find(id);
            if (backOffice == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpresaId = new SelectList(db.Empresas, "EmpresaId", "Nombre", backOffice.EmpresaId);
            return View(backOffice);
        }

        // POST: BackOffice/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdBackOffice,NombreBo,ApellidoBo,EmpresaId,Recorrido")] BackOffice backOffice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(backOffice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpresaId = new SelectList(db.Empresas, "EmpresaId", "Nombre", backOffice.EmpresaId);
            return View(backOffice);
        }

        // GET: BackOffice/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BackOffice backOffice = db.BackOffices.Find(id);
            if (backOffice == null)
            {
                return HttpNotFound();
            }
            return View(backOffice);
        }

        // POST: BackOffice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BackOffice backOffice = db.BackOffices.Find(id);
            db.BackOffices.Remove(backOffice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestorAduana-v1/Controllers/CamioneroController.cs
// Controllers/CamioneroController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestorAduana_v1.Context;
using GestorAduana_v1.Models;

namespace GestorAduana_v1.Controllers
{
    [Authorize(Roles = "Administrador,Gestor,BackOffice,Camionero")]
    public class CamioneroController : Controller
    {
        private GestorAduanasContext db = new GestorAduanasContext();

        // GET: Camionero
        public ActionResult Index(string searchDui)
        {
            var camioneros = db.Camioneros.Include(c => c.Empresa);

            if (!String.IsNullOrEmpty(searchDui))
            {
                camioneros = camioneros.Where(c => c.Dui.Contains(searchDui));
            }

            return View(camioneros.ToList());
        }

        // GET: Camionero/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Camionero camionero = db.Camioneros.Find(id);
            if (camionero == null)
            {
                return HttpNotFound();
            }
            return View(camionero);
        }

        // GET: Camionero/Create
        public ActionResult Create()
        {
            ViewBag.EmpresaId = new SelectList(db.Empresas, "EmpresaId", "Nombre");
            return View();
        }

        // POST: Camionero/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCamionero,Nombre,Apellido,Dui,Edad,Placa,QueTransporta,CantidadTransportada,EmpresaId")] Camionero camionero)
        {
            if (ModelState.IsValid)
            {
                db.Camioneros.Add(camionero);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpresaId = new SelectList(db.Empresas, "EmpresaId", "Nombre", camionero.EmpresaId);
            return View(camionero);
        }

        // GET: Camionero/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Camionero camionero = db.Camioneros.Find(id);
            if (camionero == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpresaId = new SelectList(db.Empresas, "EmpresaId", "Nombre", camionero.EmpresaId);
            return View(camionero);
        }

        // POST: Camionero/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCamionero,Nombre,Apellido,Dui,Edad,Placa,QueTransporta,CantidadTransportada,EmpresaId")] Camionero camionero)
        {
            if (ModelState.IsValid)
            {
                db.Entry(camionero).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpresaId = new SelectList(db.Empresas, "EmpresaId", "Nombre", camionero.EmpresaId);
            return View(camionero);
        }

        // GET: Camionero/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Camionero camionero = db.Camioneros.Find(id);
            if (camionero == null)
            {
                return HttpNotFound();
            }
            return View(camionero);
        }

        // POST: Camionero/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Camionero camionero = db.Camioneros.Find(id);
            db.Camioneros.Remove(camionero);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestorAduana-v1/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestorAduana_v1.Context;

namespace GestorAduana_v1.Controllers
{
    [Authorize(Roles = "BackOffice,Administrador")]
    public class EmpresaController : Controller
    {
        private GestorAduanasContext db = new GestorAduanasContext();

        // GET: Empresa
        public ActionResult Index()
        {
            return View(db.Empresas.ToList());
        }

        // GET: Empresa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresas.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // GET: Empresa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Empresa/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmpresaId,Nombre")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.Empresas.Add(empresa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(empresa);
        }

        // GET: Empresa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresas.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // POST: Empresa/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmpresaId,Nombre")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empresa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(empresa);
        }

        // GET: Empresa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresas.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // POST: Empresa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empresa empresa = db.Empresas.Find(id);
            db.Empresas.Remove(empresa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestorAduana-v1/Controllers/HomeController.cs
// HomeController.cs
using System.Web.Mvc;

namespace GestorAduana_v1.Controllers
{
    [Authorize] // Requiere autenticación para todas las acciones del controlador
    public class HomeController : Controller
    {
        // GET: Home/Index
        public ActionResult Index()
        {
            return View();
        }

        // GET: Home/About
        [AllowAnonymous] // Permite acceso sin autenticación
        public ActionResult About()
        {
            ViewBag.Message = "Descripción de la aplicación.";

            return View();
        }

        // GET: Home/Contact
        [AllowAnonymous] // Permite acceso sin autenticación
        public ActionResult Contact()
        {
            ViewBag.Message = "Página de contacto.";

            return View();
        }
    }
}

GestorAduana-v1/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestorAduana_v1.Context;

namespace GestorAduana_v1.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UsuariosController : Controller
    {
        private GestorAduanasContext db = new GestorAduanasContext();

        // GET: Usuarios
        public ActionResult Index()
        {
            return View(db.Usuarios.ToList());
        }

        // GET: Usuarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUsuario,Nombre,Apellido,Username,Contrasena,Rol")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Usuarios.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUsuario,Nombre,Apellido,Username,Contrasena,Rol")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestorAduana-v1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

GestorAduana-v1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

GestorAduana-v1/Views/Home/Index.cshtml
@* Views/Admin/Index.cshtml *@
@{
    ViewBag.Title = "Panel de Administración";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <h2 class="text-center">Bienvenido al Panel de Administración</h2>
    <p class="text-center">Desde aquí puedes gestionar las entidades principales de la aplicación.</p>

    <div class="list-group mt-4">
        @* Enlace para el CRUD de Usuarios visible solo para Administrador *@
        @if (User.IsInRole("Administrador"))
        {
            <a href="@Url.Action("Index", "Usuarios")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar Usuarios</h5>
                <p class="mb-1">Agregar, editar, eliminar y ver usuarios registrados en el sistema.</p>
            </a>
            <a href="@Url.Action("Index", "Camionero")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar Camioneros</h5>
                <p class="mb-1">Administrar la información de los camioneros registrados en el sistema.</p>
            </a>
            <a href="@Url.Action("Index", "BackOffice")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar BackOffice</h5>
                <p class="mb-1">Administrar registros de BackOffice, incluyendo datos de transporte y rutas.</p>
            </a>
            <a href="@Url.Action("Index", "Empresa")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar Empresas</h5>
                <p class="mb-1">Agregar, editar, eliminar y ver empresas asociadas a las unidades de transporte.</p>
            </a>
        }

        @* Enlace para el CRUD de Camioneros visible para Gestor *@
        @if (User.IsInRole("Gestor"))
        {
            <a href="@Url.Action("Index", "Camionero")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar Camioneros</h5>
                <p class="mb-1">Administrar la información de los camioneros registrados en el sistema.</p>
            </a>
            <a href="@Url.Action("Index", "BackOffice")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar BackOffice</h5>
                <p class="mb-1">Administrar registros de BackOffice, incluyendo datos de transporte y rutas.</p>
            </a>
        }

        @* Enlace para el CRUD de Camioneros visible para Camionero *@
        @if ( User.IsInRole("Camionero"))
        {
            <a href="@Url.Action("Index", "Camionero")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar Camioneros</h5>
                <p class="mb-1">Administrar la información de los camioneros registrados en el sistema.</p>
            </a>
        }

        @* Enlace para el CRUD de Empresas visible solo para Administrador y BackOffice *@
        @if (User.IsInRole("BackOffice"))
        {
            <a href="@Url.Action("Index", "Empresa")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar Empresas</h5>
                <p class="mb-1">Agregar, editar, eliminar y ver empresas asociadas a las unidades de transporte.</p>
            </a>
            <a href="@Url.Action("Index", "BackOffice")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar BackOffice</h5>
                <p class="mb-1">Administrar registros de BackOffice, incluyendo datos de transporte y rutas.</p>
            </a>
            <a href="@Url.Action("Index", "Camionero")" class="list-group-item list-group-item-action">
                <h5 class="mb-1">Gestionar Camioneros</h5>
                <p class="mb-1">Administrar la información de los camioneros registrados en el sistema.</p>
            </a>
        }
    </div>
</div>